### ISSUE TITLE
Check partition in SD card before resizing it to prevent resizing failure

### ISSUE THREAD

**Issue by dragonation** [od-contrib/buildroot-rg350-old-kernel#13]
```
# Unmount data partition before resizing for faster resizing.
unmount_data_partition

# Check partition to prevent resize from failling
e2fsck -f /dev/${DEVICE}p${PART_NUM}
```
According to `board/opendingux/package/od-imager/od-imager.mk`. The od-imager repo is configured as glebm's one, however there is no place to write an issue on that one (maybe disabled). So I have to write it here. There is already a pull request on that repo mention the bug six months ago. 

The code above is my version to resolve it. Currently, it seems the generated bin and zip file has a broken partition table, which will cause a new flushed system will always fail to resize data partition

**Comment by glebm** [comment]
Thanks for flagging this! Resize worked for my SD card in the older version as well, I hope this fixes it for everyone.

**Comment by dragonation** [comment]
Yes, the version before yesterday, (it is the first version I built), everything ok on the partition table for resizing. But soon, it broken... 

Tested 4 times, dirty build, clean build all broken... I don't known what happened to the codes caused the bug, maybe bin size mismatch or somewhere overflow?

**Comment by glebm** [comment]
Did the commit above fix it for you?

**Comment by dragonation** [comment]
yes, it works. currently, i use the code above to ensure resizefs ok
