### ISSUE TITLE
Is there a plan to upgrade the kernel to 5.x?

### ISSUE THREAD

**Issue by KatyushaScarlet** [od-contrib/buildroot-rg350-old-kernel#14]
I noticed that they have already add support for rg350/rg350m in kernel 5.9.

https://github.com/OpenDingux/linux/tree/jz-5.9

ROM & Toolchain are here:

https://zcrc.me/

**Comment by dragonation** [comment]
It sounds good, but more tests should be done before the kernel upgrade, I think.

In my opinion, userland app, foundation library and modern toolchain is more important than the kernel to a retro game devices.

When the userland comes stable, at least, I, myself, will try to upgrade the kernel. Just like my working laptop, using kernel 5.x.

**Comment by KatyushaScarlet** [comment]
> It sounds good, but more tests should be done before the kernel upgrade, I think.
> 
> In my opinion, userland app, foundation library and modern toolchain is more important than the kernel to a retro game devices.
> 
> When the userland comes stable, at least, I, myself, will try to upgrade the kernel. Just like my working laptop, using kernel 5.x.

Thanks for your reply!

**Comment by KatyushaScarlet** [comment]
> It sounds good, but more tests should be done before the kernel upgrade, I think.
> 
> In my opinion, userland app, foundation library and modern toolchain is more important than the kernel to a retro game devices.
> 
> When the userland comes stable, at least, I, myself, will try to upgrade the kernel. Just like my working laptop, using kernel 5.x.

https://zcrc.me/opendingux/2020/06/09/update-on-gcw-zero-20200531.html

According to their description, due to the new kernel and GPU driver, IO performance is significantly improved, and the GPU is faster in most areas.

I just tried the new kernel and firmware, and found that the MTP mode was added(just like on Android).

**Comment by glebm** [comment]
There are still a few issues with the new kernel. For example, the old kernel has an OpenDingux-specific `linkdev` kernel driver that merges the left and right joystick devices into one device, and handles switching between controller and keyboard mode (`X-OD-NeedsJoystick=true`). For the new kernel, Paul instead decided to implement controller handling in userland in SDL2 but that's not done yet.

Here we can work on userland and upstream it to OpenDingux bit-by-bit. This is what I've been doing so far.

Once the upstream OpenDingux is fully functional, we can switch to it.

**Comment by glebm** [comment]
Haven't looked at OpenDingux for a few months, trying the update now from http://od.abstraction.se/opendingux/latest/gcw0-update-2020-10-08.opk
