### ISSUE TITLE
Makefile:184: *** multiple target patterns.  Stop.

### ISSUE THREAD

**Issue by KatyushaScarlet** [od-contrib/buildroot-rg350-old-kernel#3]
When I'm trying to run

`make rg350_defconfig BR2_EXTERNAL=board/opendingux:opks`

`board/opendingux/gcw0/make_initial_image.sh rg350`

or

`make rg350m_defconfig BR2_EXTERNAL=board/opendingux:opks`

`board/opendingux/gcw0/make_initial_image.sh rg350m`

I got this error

**Comment by KatyushaScarlet** [comment]
Hi, I wonder what is ":opks" means?
Is this necessary?

Thanks!

**Comment by KatyushaScarlet** [comment]
After I remove the ":opks", it works fine

**Comment by glebm** [comment]
`opks` is a git submodule that contains several OPK packages

You may need to run this first to get the submodules

```
git submodule update --recursive
```

**Comment by KatyushaScarlet** [comment]
> git submodule update --recursive

I suggest adding this instruction to the README file.

**Comment by glebm** [comment]
Done!

**Comment by KatyushaScarlet** [comment]
Thanks!
