### ISSUE TITLE
love2d in buildroot is no longer available

### ISSUE THREAD

**Issue by KatyushaScarlet** [od-contrib/buildroot-rg350-old-kernel#4]
love2d aeefcc6 Downloading
abort: HTTP Error 404: Not Found
--2020-10-08 11:55:28--  http://sources.buildroot.net/love2d/love2d-aeefcc6.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.0.37, 104.26.1.37, 172.67.72.56
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.0.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-08 11:55:29 ERROR 404: Not Found.

--2020-10-08 11:55:29--  http://sources.buildroot.net/love2d-aeefcc6.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 172.67.72.56, 104.26.0.37, 104.26.1.37
Connecting to sources.buildroot.net (sources.buildroot.net)|172.67.72.56|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-08 11:55:29 ERROR 404: Not Found.

make: *** [package/pkg-generic.mk:171: /home/katyusha/rg350/buildroot-rg350-old-kernel/output/build/love2d-aeefcc6/.stamp_downloaded] Error 1

**Comment by KatyushaScarlet** [comment]
Maybe it should be remove？

**Comment by glebm** [comment]
I think this could be updated to the current git repository:

https://github.com/od-contrib/buildroot-rg350-old-kernel/blob/4f9dfeb1c8efa57c144375ad19c8f922e8f078fd/board/opendingux/package/love2d/love2d.mk#L7-L8

The git repository is at https://github.com/love2d/love

**Comment by KatyushaScarlet** [comment]
This package is set to download from sources.buildroot.net instead of downloading and compiling from the git repository.
I don't know much about buildroot, maybe the config file needs to be modified?

**Comment by glebm** [comment]
I think it goes to hg first, but that repo is down, so it tries the sources.buildroot.net fallback but it's not there either.

You can try changing the 2 lines above to the following:

```make
LOVE2D_SITE = $(call github,love2d,love,$(LOVE2D_VERSION))
```

The `LOVE2D_VERSION` will need to be changed as well because they migrated from Mercurial to Git.

The corresponding commit date should be around 17 Jul 2014.

**Comment by KatyushaScarlet** [comment]
OK, I will try the [e87fbdc ](https://github.com/love2d/love/commit/e87fbdcaaf3537c984b164da7378d125c961ec8f) version

**Comment by glebm** [comment]
One of the files the buildroot patches, glad.cpp, doesn't even exist in that version.
It first appeared on Aug 18 2014 (`git log -- src/libraries/glad/glad.cpp`)

I'm trying various version to find a working one
