### ISSUE TITLE
 Lack of sharpness downscaling and upscaling function

### ISSUE THREAD

**Issue by KatyushaScarlet** [od-contrib/buildroot-rg350-old-kernel#5]
In the original firmware of RG350, you can adjust the smoothness of the screen by pressing the power button + up or down.
This feature should also be open source, but it seems not in the 350m kernel of this repo?

**Comment by glebm** [comment]
This seems like a bug. Here is some investigation:

The power button functions are managed by the `pwswd` library. This repo should use the same `pwswd` library as the original firmware.

`pwswd` adjusts sharpenss by writing to these files:

* /sys/devices/platform/jz-lcd.0/sharpness_downscaling
* /sys/devices/platform/jz-lcd.0/sharpness_upscaling

(source: https://github.com/tonyjih/RG350_pwswd/commit/58133f46363abaf80179f041e75aa500eb844316)

**Comment by glebm** [comment]
These attributes are defined in the Linux kernel here:

https://github.com/tonyjih/RG350_linux/blob/d915bcac07f2ab2e797c425630cfcf9f7c2b4c8c/drivers/video/jz4770_fb.c#L1172-L1173

**Comment by glebm** [comment]
There is a comment here about the sharpness value range for 320x240 screens:

https://github.com/tonyjih/RG350_linux/blob/b713e4eaaba4b360d996e2b8e5fae4db8ee5fab3/drivers/video/jz4770_fb.c#L468-L471

Maybe the range should be different for 640x480?

**Comment by glebm** [comment]
Ingenic doesn't seem to have any documentation on the IPU on their FTP server

I've managed to find a very old draft for jz4750 on the internet: [Jz4750_31_ipu_spec.pdf](https://github.com/od-contrib/buildroot-rg350-old-kernel/files/5360797/Jz4750_31_ipu_spec.pdf)

**Comment by glebm** [comment]
I've verified that the values of `/sys/devices/platform/jz-lcd.0/sharpness_*` change correctly on RG350m as the Power+Up/Down is pressed. The problem is likely in the kernel.

**Comment by KatyushaScarlet** [comment]
> Ingenic doesn't seem to have any documentation on the IPU on their FTP server
> 
> I've managed to find a very old draft for jz4750 on the internet: [Jz4750_31_ipu_spec.pdf](https://github.com/od-contrib/buildroot-rg350-old-kernel/files/5360797/Jz4750_31_ipu_spec.pdf)

ftp://grids.be/mirror/ftp.ingenic.cn/
I found something here, will this help?

**Comment by glebm** [comment]
Thanks for the link, I haven't found any IPU documents there but I'm not really qualified to fix this anyway.

Which app have you tried this with by the way? Did it work for you on the original RG350m firmware?

**Comment by KatyushaScarlet** [comment]
1.I have tried PCSX4ALL and ReGBA emulator.

2.Yes, they work fine on the original RG350m firmware.

**Comment by glebm** [comment]
This might be a miscompilation issue, because we use a newer GCC for compiling this ancient kernel. I think we might have to try compiling the kernel with the old GCC.

I hope I'll be able to set it up so that the kernel is compiled with the old GCC and the rest of the buildroot is compiled with a recent GCC.

**Comment by glebm** [comment]
Compiling with the old kernel fixes scaling but doesn't fix OpenGL flickering (so that one probably comes from etnaviv drivers).

By the way, in ReGBA, do you have scaling set to "Hardware"?

**Comment by KatyushaScarlet** [comment]
> Compiling with the old kernel fixes scaling but doesn't fix OpenGL flickering (so that one probably comes from etnaviv drivers).
> 
> By the way, in ReGBA, do you have scaling set to "Hardware"?

Sorry, it was my fault :(
In the original RG350M firmware, the ReGBA set to Hardware by default, but in this firmware, it seems that it set to Stretch by default.
I only tested the two firmwares by simply switching the system TF card, but did not notice the emulator settings.
I am so sorry for wasting your time.

**Comment by glebm** [comment]
No worries, good things came out of this:

1. Separating the kernel build from the userland build allowed us to upgrade from GCC 5 all the way to GCC 10!
2. We noticed that ReGBA doesn't default to "Hardware" (it should), I'll investigate that separately.

**Comment by glebm** [comment]
I've switched the local pack to a different version of ReGBA here: https://github.com/od-contrib/buildroot-rg350-old-kernel/commit/108748437367e4752c2a2e76cd4c6f6689c81705

Hopefully it'll default to hardware scaling
