### ISSUE TITLE
Framedrop in GMenu2X of RG350M

### ISSUE THREAD

**Issue by KatyushaScarlet** [od-contrib/buildroot-rg350-old-kernel#6]
When using the L1 R1 button to switch parts, the part above GMenu2X of RG350M cannot scroll smoothly like RG350

**Comment by glebm** [comment]
Probably not a framedrop, just very slow animation speed

**Comment by KatyushaScarlet** [comment]
It seems like it runs at 30fps on RG350M, but 60fps on RG350.
