### ISSUE TITLE
Broken dependency for "glutexto"

### ISSUE THREAD

**Issue by shagu** [od-contrib/buildroot-rg350-old-kernel#7]
Hi,
I've followed the instructions in the README and get a build failure due to a broken dependency on the default target. However, building "world" seems to work:

```
$ make rg350_defconfig BR2_EXTERNAL=board/opendingux:opks
$ make
Makefile:578: *** sparrow3d is in the dependency chain of glutexto that has added it to its _DEPENDENCIES variable without selecting it or depending on it from Config.in.  Stop.
```

*I'm not very familiar with buildroot, so I disabled glutexto for now, which seems to work*

**Comment by glebm** [comment]
Ah, dependencies are only checked during `make` (with no arguments)

The sparrow3d package is only built as a build dependency (it is then linked statically) but we didn't tell the buildroot that.
